version: "3"
services:
  db:
    image: mongo:3.4.4
    volumes:
      - ./data/:/data/db
  app:
    build: .
    ports:
      - 3000:3000
    #links:
    #  - db
    volumes:
      - ./:/usr/src/app/
